server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:}
spring:
  cache:
    cache-names:
      - rate-limit-bucket
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    parent-committee:
      host: ${PARENT_COMMITTEE_MAIL_HOST}
      port: ${PARENT_COMMITTEE_MAIL_PORT}
      username: ${PARENT_COMMITTEE_MAIL_USERNAME}
      password: ${PARENT_COMMITTEE_MAIL_PASSWORD}
      properties:
        'mail.transport.protocol': 'smtp'
        'mail.smtp.auth': 'true'
        'mail.smtp.ssl.enable': 'true'
        'mail.smtp.starttls.enable': 'true'
bucket4j:
  enabled: true
  filters:
    - url: /kindergarten/elternausschuss/nachricht/absenden
      cache-name: rate-limit-bucket
      rate-limits:
        - bandwidths:
            - capacity: 1
              time: 1
              unit: minutes
              refill-speed: interval