server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:}
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true