version: '3.8'
services:
  db:
    image: mariadb:10.10
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      MYSQL_DATABASE: foerderverein
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    restart: always
    ports:
      - '3306:3306'