version: '3.8'
services:
  db:
    image: db:latest
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      MYSQL_DATABASE: sandbox
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    restart: always
    ports:
      - '3306:3306'
